default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
    - id: flake8
      name: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    - id: mypy
      name: mypy
